import {
  ANTHROPIC_API_KEY,
  AZURE_OPENAI_API_VERSION,
  AZURE_OPENAI_DEPLOYMENT,
  AZURE_OPENAI_ENDPOINT,
  AZURE_OPENAI_KEY,
  SQAI_ANTHROPIC_API_KEY,
  SQAI_AZURE_OPENAI_API_VERSION,
  SQAI_AZURE_OPENAI_DEPLOYMENT,
  SQAI_AZURE_OPENAI_ENDPOINT,
  SQAI_AZURE_OPENAI_INIT_CONFIG_JSON,
  SQAI_AZURE_OPENAI_KEY,
  SQAI_AZURE_OPENAI_SCOPE,
  SQAI_GROUNDING_ANTHROPIC_API_KEY,
  SQAI_GROUNDING_AZURE_OPENAI_API_VERSION,
  SQAI_GROUNDING_AZURE_OPENAI_DEPLOYMENT,
  SQAI_GROUNDING_AZURE_OPENAI_ENDPOINT,
  SQAI_GROUNDING_AZURE_OPENAI_INIT_CONFIG_JSON,
  SQAI_GROUNDING_AZURE_OPENAI_KEY,
  SQAI_GROUNDING_AZURE_OPENAI_SCOPE,
  SQAI_GROUNDING_MODEL_NAME,
  SQAI_GROUNDING_OPENAI_API_KEY,
  SQAI_GROUNDING_OPENAI_BASE_URL,
  SQAI_GROUNDING_OPENAI_HTTP_PROXY,
  SQAI_GROUNDING_OPENAI_INIT_CONFIG_JSON,
  SQAI_GROUNDING_OPENAI_SOCKS_PROXY,
  SQAI_GROUNDING_OPENAI_USE_AZURE,
  SQAI_GROUNDING_USE_ANTHROPIC_SDK,
  SQAI_GROUNDING_USE_AZURE_OPENAI,
  SQAI_GROUNDING_VL_MODE,
  SQAI_MODEL_NAME,
  SQAI_OPENAI_API_KEY,
  SQAI_OPENAI_BASE_URL,
  SQAI_OPENAI_HTTP_PROXY,
  SQAI_OPENAI_INIT_CONFIG_JSON,
  SQAI_OPENAI_SOCKS_PROXY,
  SQAI_OPENAI_USE_AZURE,
  SQAI_PLANNING_ANTHROPIC_API_KEY,
  SQAI_PLANNING_AZURE_OPENAI_API_VERSION,
  SQAI_PLANNING_AZURE_OPENAI_DEPLOYMENT,
  SQAI_PLANNING_AZURE_OPENAI_ENDPOINT,
  SQAI_PLANNING_AZURE_OPENAI_INIT_CONFIG_JSON,
  SQAI_PLANNING_AZURE_OPENAI_KEY,
  SQAI_PLANNING_AZURE_OPENAI_SCOPE,
  SQAI_PLANNING_MODEL_NAME,
  SQAI_PLANNING_OPENAI_API_KEY,
  SQAI_PLANNING_OPENAI_BASE_URL,
  SQAI_PLANNING_OPENAI_HTTP_PROXY,
  SQAI_PLANNING_OPENAI_INIT_CONFIG_JSON,
  SQAI_PLANNING_OPENAI_SOCKS_PROXY,
  SQAI_PLANNING_OPENAI_USE_AZURE,
  SQAI_PLANNING_USE_ANTHROPIC_SDK,
  SQAI_PLANNING_USE_AZURE_OPENAI,
  SQAI_PLANNING_VL_MODE,
  SQAI_USE_ANTHROPIC_SDK,
  SQAI_USE_AZURE_OPENAI,
  SQAI_VL_MODE,
  SQAI_VQA_ANTHROPIC_API_KEY,
  SQAI_VQA_AZURE_OPENAI_API_VERSION,
  SQAI_VQA_AZURE_OPENAI_DEPLOYMENT,
  SQAI_VQA_AZURE_OPENAI_ENDPOINT,
  SQAI_VQA_AZURE_OPENAI_INIT_CONFIG_JSON,
  SQAI_VQA_AZURE_OPENAI_KEY,
  SQAI_VQA_AZURE_OPENAI_SCOPE,
  // VQA
  SQAI_VQA_MODEL_NAME,
  SQAI_VQA_OPENAI_API_KEY,
  SQAI_VQA_OPENAI_BASE_URL,
  SQAI_VQA_OPENAI_HTTP_PROXY,
  SQAI_VQA_OPENAI_INIT_CONFIG_JSON,
  SQAI_VQA_OPENAI_SOCKS_PROXY,
  SQAI_VQA_OPENAI_USE_AZURE,
  SQAI_VQA_USE_ANTHROPIC_SDK,
  SQAI_VQA_USE_AZURE_OPENAI,
  SQAI_VQA_VL_MODE,
  OPENAI_API_KEY,
  OPENAI_BASE_URL,
  OPENAI_USE_AZURE,
} from './types';

interface IModelConfigKeys {
  modelName: string;
  /**
   * proxy
   */
  socksProxy: string;
  httpProxy: string;
  /**
   * OpenAI
   */
  openaiBaseURL: string;
  openaiApiKey: string;
  openaiExtraConfig: string;
  /**
   * Azure
   */
  openaiUseAzureDeprecated: string;
  useAzureOpenai: string;
  azureOpenaiScope: string;
  azureOpenaiKey: string;
  azureOpenaiEndpoint: string;
  azureOpenaiApiVersion: string;
  azureOpenaiDeployment: string;
  azureExtraConfig: string;
  /**
   * Anthropic
   */
  useAnthropicSdk: string;
  anthropicApiKey: string;
  /**
   * Extra
   */
  vlMode: string;
}

export const VQA_MODEL_CONFIG_KEYS: IModelConfigKeys = {
  modelName: SQAI_VQA_MODEL_NAME,
  /**
   * proxy
   */
  socksProxy: SQAI_VQA_OPENAI_SOCKS_PROXY,
  httpProxy: SQAI_VQA_OPENAI_HTTP_PROXY,
  /**
   * OpenAI
   */
  openaiBaseURL: SQAI_VQA_OPENAI_BASE_URL,
  openaiApiKey: SQAI_VQA_OPENAI_API_KEY,
  openaiExtraConfig: SQAI_VQA_OPENAI_INIT_CONFIG_JSON,
  /**
   * Azure
   */
  openaiUseAzureDeprecated: SQAI_VQA_OPENAI_USE_AZURE,
  useAzureOpenai: SQAI_VQA_USE_AZURE_OPENAI,
  azureOpenaiScope: SQAI_VQA_AZURE_OPENAI_SCOPE,
  azureOpenaiKey: SQAI_VQA_AZURE_OPENAI_KEY,
  azureOpenaiEndpoint: SQAI_VQA_AZURE_OPENAI_ENDPOINT,
  azureOpenaiApiVersion: SQAI_VQA_AZURE_OPENAI_API_VERSION,
  azureOpenaiDeployment: SQAI_VQA_AZURE_OPENAI_DEPLOYMENT,
  azureExtraConfig: SQAI_VQA_AZURE_OPENAI_INIT_CONFIG_JSON,
  /**
   * Anthropic
   */
  useAnthropicSdk: SQAI_VQA_USE_ANTHROPIC_SDK,
  anthropicApiKey: SQAI_VQA_ANTHROPIC_API_KEY,
  /**
   * Extra
   */
  vlMode: SQAI_VQA_VL_MODE,
} as const;

export const GROUNDING_MODEL_CONFIG_KEYS: IModelConfigKeys = {
  modelName: SQAI_GROUNDING_MODEL_NAME,
  /**
   * proxy
   */
  socksProxy: SQAI_GROUNDING_OPENAI_SOCKS_PROXY,
  httpProxy: SQAI_GROUNDING_OPENAI_HTTP_PROXY,
  /**
   * OpenAI
   */
  openaiBaseURL: SQAI_GROUNDING_OPENAI_BASE_URL,
  openaiApiKey: SQAI_GROUNDING_OPENAI_API_KEY,
  openaiExtraConfig: SQAI_GROUNDING_OPENAI_INIT_CONFIG_JSON,
  /**
   * Azure
   */
  openaiUseAzureDeprecated: SQAI_GROUNDING_OPENAI_USE_AZURE,
  useAzureOpenai: SQAI_GROUNDING_USE_AZURE_OPENAI,
  azureOpenaiScope: SQAI_GROUNDING_AZURE_OPENAI_SCOPE,
  azureOpenaiKey: SQAI_GROUNDING_AZURE_OPENAI_KEY,
  azureOpenaiEndpoint: SQAI_GROUNDING_AZURE_OPENAI_ENDPOINT,
  azureOpenaiApiVersion: SQAI_GROUNDING_AZURE_OPENAI_API_VERSION,
  azureOpenaiDeployment: SQAI_GROUNDING_AZURE_OPENAI_DEPLOYMENT,
  azureExtraConfig: SQAI_GROUNDING_AZURE_OPENAI_INIT_CONFIG_JSON,
  /**
   * Anthropic
   */
  useAnthropicSdk: SQAI_GROUNDING_USE_ANTHROPIC_SDK,
  anthropicApiKey: SQAI_GROUNDING_ANTHROPIC_API_KEY,
  /**
   * Extra
   */
  vlMode: SQAI_GROUNDING_VL_MODE,
} as const;

export const PLANNING_MODEL_CONFIG_KEYS: IModelConfigKeys = {
  modelName: SQAI_PLANNING_MODEL_NAME,
  /**
   * proxy
   */
  socksProxy: SQAI_PLANNING_OPENAI_SOCKS_PROXY,
  httpProxy: SQAI_PLANNING_OPENAI_HTTP_PROXY,
  /**
   * OpenAI
   */
  openaiBaseURL: SQAI_PLANNING_OPENAI_BASE_URL,
  openaiApiKey: SQAI_PLANNING_OPENAI_API_KEY,
  openaiExtraConfig: SQAI_PLANNING_OPENAI_INIT_CONFIG_JSON,
  /**
   * Azure
   */
  openaiUseAzureDeprecated: SQAI_PLANNING_OPENAI_USE_AZURE,
  useAzureOpenai: SQAI_PLANNING_USE_AZURE_OPENAI,
  azureOpenaiScope: SQAI_PLANNING_AZURE_OPENAI_SCOPE,
  azureOpenaiKey: SQAI_PLANNING_AZURE_OPENAI_KEY,
  azureOpenaiEndpoint: SQAI_PLANNING_AZURE_OPENAI_ENDPOINT,
  azureOpenaiApiVersion: SQAI_PLANNING_AZURE_OPENAI_API_VERSION,
  azureOpenaiDeployment: SQAI_PLANNING_AZURE_OPENAI_DEPLOYMENT,
  azureExtraConfig: SQAI_PLANNING_AZURE_OPENAI_INIT_CONFIG_JSON,
  /**
   * Anthropic
   */
  useAnthropicSdk: SQAI_PLANNING_USE_ANTHROPIC_SDK,
  anthropicApiKey: SQAI_PLANNING_ANTHROPIC_API_KEY,
  /**
   * Extra
   */
  vlMode: SQAI_PLANNING_VL_MODE,
} as const;

// modelConfig return default
export const DEFAULT_MODEL_CONFIG_KEYS: IModelConfigKeys = {
  modelName: SQAI_MODEL_NAME,
  /**
   * proxy
   */
  socksProxy: SQAI_OPENAI_SOCKS_PROXY,
  httpProxy: SQAI_OPENAI_HTTP_PROXY,
  /**
   * OpenAI
   */
  openaiBaseURL: SQAI_OPENAI_BASE_URL,
  openaiApiKey: SQAI_OPENAI_API_KEY,
  openaiExtraConfig: SQAI_OPENAI_INIT_CONFIG_JSON,
  /**
   * Azure
   */
  openaiUseAzureDeprecated: SQAI_OPENAI_USE_AZURE,
  useAzureOpenai: SQAI_USE_AZURE_OPENAI,
  azureOpenaiScope: SQAI_AZURE_OPENAI_SCOPE,
  azureOpenaiKey: SQAI_AZURE_OPENAI_KEY,
  azureOpenaiEndpoint: SQAI_AZURE_OPENAI_ENDPOINT,
  azureOpenaiApiVersion: SQAI_AZURE_OPENAI_API_VERSION,
  azureOpenaiDeployment: SQAI_AZURE_OPENAI_DEPLOYMENT,
  azureExtraConfig: SQAI_AZURE_OPENAI_INIT_CONFIG_JSON,
  /**
   * Anthropic
   */
  useAnthropicSdk: SQAI_USE_ANTHROPIC_SDK,
  anthropicApiKey: SQAI_ANTHROPIC_API_KEY,
  /**
   * Extra
   */
  vlMode: SQAI_VL_MODE,
} as const;

// read from process.env
export const DEFAULT_MODEL_CONFIG_KEYS_LEGACY: IModelConfigKeys = {
  modelName: SQAI_MODEL_NAME,
  /**
   * proxy
   */
  socksProxy: SQAI_OPENAI_SOCKS_PROXY,
  httpProxy: SQAI_OPENAI_HTTP_PROXY,
  /**
   * OpenAI
   */
  openaiBaseURL: OPENAI_BASE_URL,
  openaiApiKey: OPENAI_API_KEY,
  openaiExtraConfig: SQAI_OPENAI_INIT_CONFIG_JSON,
  /**
   * Azure
   */
  openaiUseAzureDeprecated: OPENAI_USE_AZURE,
  useAzureOpenai: SQAI_USE_AZURE_OPENAI,
  azureOpenaiScope: SQAI_AZURE_OPENAI_SCOPE,
  azureOpenaiKey: AZURE_OPENAI_KEY,
  azureOpenaiEndpoint: AZURE_OPENAI_ENDPOINT,
  azureOpenaiApiVersion: AZURE_OPENAI_API_VERSION,
  azureOpenaiDeployment: AZURE_OPENAI_DEPLOYMENT,
  azureExtraConfig: SQAI_AZURE_OPENAI_INIT_CONFIG_JSON,
  /**
   * Anthropic
   */
  useAnthropicSdk: SQAI_USE_ANTHROPIC_SDK,
  anthropicApiKey: ANTHROPIC_API_KEY,
  /**
   * Extra
   */
  vlMode: 'DEFAULT_MODEL_CONFIG_KEYS has no vlMode key',
} as const;
