// config keys
export const SQAI_OPENAI_INIT_CONFIG_JSON =
  'SQAI_OPENAI_INIT_CONFIG_JSON';
export const SQAI_MODEL_NAME = 'SQAI_MODEL_NAME';
export const SQAI_LANGSMITH_DEBUG = 'SQAI_LANGSMITH_DEBUG';
export const SQAI_DEBUG_AI_PROFILE = 'SQAI_DEBUG_AI_PROFILE';
export const SQAI_DEBUG_AI_RESPONSE = 'SQAI_DEBUG_AI_RESPONSE';
export const SQAI_DANGEROUSLY_PRINT_ALL_CONFIG =
  'SQAI_DANGEROUSLY_PRINT_ALL_CONFIG';
export const SQAI_DEBUG_MODE = 'SQAI_DEBUG_MODE';
export const SQAI_MCP_USE_PUPPETEER_MODE =
  'SQAI_MCP_USE_PUPPETEER_MODE';
export const SQAI_MCP_CHROME_PATH = 'SQAI_MCP_CHROME_PATH';
export const SQAI_MCP_ANDROID_MODE = 'SQAI_MCP_ANDROID_MODE';
export const DOCKER_CONTAINER = 'DOCKER_CONTAINER';
export const SQAI_FORCE_DEEP_THINK = 'SQAI_FORCE_DEEP_THINK';

export const SQAI_OPENAI_SOCKS_PROXY = 'SQAI_OPENAI_SOCKS_PROXY';
export const SQAI_OPENAI_HTTP_PROXY = 'SQAI_OPENAI_HTTP_PROXY';
export const OPENAI_API_KEY = 'OPENAI_API_KEY';
export const OPENAI_BASE_URL = 'OPENAI_BASE_URL';
export const OPENAI_MAX_TOKENS = 'OPENAI_MAX_TOKENS';

export const SQAI_ADB_PATH = 'SQAI_ADB_PATH';
export const SQAI_ADB_REMOTE_HOST = 'SQAI_ADB_REMOTE_HOST';
export const SQAI_ADB_REMOTE_PORT = 'SQAI_ADB_REMOTE_PORT';
export const SQAI_ANDROID_IME_STRATEGY = 'SQAI_ANDROID_IME_STRATEGY';

export const SQAI_IOS_DEVICE_UDID = 'SQAI_IOS_DEVICE_UDID';
export const SQAI_IOS_SIMULATOR_UDID = 'SQAI_IOS_SIMULATOR_UDID';

export const SQAI_CACHE = 'SQAI_CACHE';
export const SQAI_USE_VLM_UI_TARS = 'SQAI_USE_VLM_UI_TARS';
export const SQAI_USE_QWEN_VL = 'SQAI_USE_QWEN_VL';
export const SQAI_USE_QWEN3_VL = 'SQAI_USE_QWEN3_VL';
export const SQAI_USE_DOUBAO_VISION = 'SQAI_USE_DOUBAO_VISION';
export const SQAI_USE_GEMINI = 'SQAI_USE_GEMINI';
export const SQAI_USE_VL_MODEL = 'SQAI_USE_VL_MODEL';
export const MATCH_BY_POSITION = 'MATCH_BY_POSITION';
export const SQAI_API_TYPE = 'SQAI-API-TYPE';
export const SQAI_REPORT_TAG_NAME = 'SQAI_REPORT_TAG_NAME';

export const SQAI_REPLANNING_CYCLE_LIMIT =
  'SQAI_REPLANNING_CYCLE_LIMIT';

export const SQAI_PREFERRED_LANGUAGE = 'SQAI_PREFERRED_LANGUAGE';

export const SQAI_USE_AZURE_OPENAI = 'SQAI_USE_AZURE_OPENAI';
export const SQAI_AZURE_OPENAI_SCOPE = 'SQAI_AZURE_OPENAI_SCOPE';
export const SQAI_AZURE_OPENAI_INIT_CONFIG_JSON =
  'SQAI_AZURE_OPENAI_INIT_CONFIG_JSON';

export const SQAI_CACHE_MAX_FILENAME_LENGTH =
  'SQAI_CACHE_MAX_FILENAME_LENGTH';

export const AZURE_OPENAI_ENDPOINT = 'AZURE_OPENAI_ENDPOINT';
export const AZURE_OPENAI_KEY = 'AZURE_OPENAI_KEY';
export const AZURE_OPENAI_API_VERSION = 'AZURE_OPENAI_API_VERSION';
export const AZURE_OPENAI_DEPLOYMENT = 'AZURE_OPENAI_DEPLOYMENT';

export const SQAI_USE_ANTHROPIC_SDK = 'SQAI_USE_ANTHROPIC_SDK';
export const ANTHROPIC_API_KEY = 'ANTHROPIC_API_KEY';

export const SQAI_RUN_DIR = 'SQAI_RUN_DIR';

// default new
export const SQAI_OPENAI_BASE_URL = 'SQAI_OPENAI_BASE_URL';
export const SQAI_OPENAI_API_KEY = 'SQAI_OPENAI_API_KEY';
export const SQAI_OPENAI_USE_AZURE = 'SQAI_OPENAI_USE_AZURE';
export const SQAI_AZURE_OPENAI_KEY = 'SQAI_AZURE_OPENAI_KEY';
export const SQAI_AZURE_OPENAI_ENDPOINT = 'SQAI_AZURE_OPENAI_ENDPOINT';
export const SQAI_AZURE_OPENAI_API_VERSION =
  'SQAI_AZURE_OPENAI_API_VERSION';
export const SQAI_AZURE_OPENAI_DEPLOYMENT =
  'SQAI_AZURE_OPENAI_DEPLOYMENT';
export const SQAI_ANTHROPIC_API_KEY = 'SQAI_ANTHROPIC_API_KEY';
export const SQAI_VL_MODE = 'SQAI_VL_MODE';

// VQA
export const SQAI_VQA_MODEL_NAME = 'SQAI_VQA_MODEL_NAME';
export const SQAI_VQA_OPENAI_SOCKS_PROXY =
  'SQAI_VQA_OPENAI_SOCKS_PROXY';
export const SQAI_VQA_OPENAI_HTTP_PROXY = 'SQAI_VQA_OPENAI_HTTP_PROXY';
export const SQAI_VQA_OPENAI_BASE_URL = 'SQAI_VQA_OPENAI_BASE_URL';
export const SQAI_VQA_OPENAI_API_KEY = 'SQAI_VQA_OPENAI_API_KEY';
export const SQAI_VQA_OPENAI_INIT_CONFIG_JSON =
  'SQAI_VQA_OPENAI_INIT_CONFIG_JSON';
export const SQAI_VQA_OPENAI_USE_AZURE = 'SQAI_VQA_OPENAI_USE_AZURE';
export const SQAI_VQA_USE_AZURE_OPENAI = 'SQAI_VQA_USE_AZURE_OPENAI';
export const SQAI_VQA_AZURE_OPENAI_SCOPE =
  'SQAI_VQA_AZURE_OPENAI_SCOPE';
export const SQAI_VQA_AZURE_OPENAI_KEY = 'SQAI_VQA_AZURE_OPENAI_KEY';
export const SQAI_VQA_AZURE_OPENAI_ENDPOINT =
  'SQAI_VQA_AZURE_OPENAI_ENDPOINT';
export const SQAI_VQA_AZURE_OPENAI_API_VERSION =
  'SQAI_VQA_AZURE_OPENAI_API_VERSION';
export const SQAI_VQA_AZURE_OPENAI_DEPLOYMENT =
  'SQAI_VQA_AZURE_OPENAI_DEPLOYMENT';
export const SQAI_VQA_AZURE_OPENAI_INIT_CONFIG_JSON =
  'SQAI_VQA_AZURE_OPENAI_INIT_CONFIG_JSON';
export const SQAI_VQA_USE_ANTHROPIC_SDK = 'SQAI_VQA_USE_ANTHROPIC_SDK';
export const SQAI_VQA_ANTHROPIC_API_KEY = 'SQAI_VQA_ANTHROPIC_API_KEY';
export const SQAI_VQA_VL_MODE = 'SQAI_VQA_VL_MODE';

// PLANNING
export const SQAI_PLANNING_MODEL_NAME = 'SQAI_PLANNING_MODEL_NAME';
export const SQAI_PLANNING_OPENAI_SOCKS_PROXY =
  'SQAI_PLANNING_OPENAI_SOCKS_PROXY';
export const SQAI_PLANNING_OPENAI_HTTP_PROXY =
  'SQAI_PLANNING_OPENAI_HTTP_PROXY';
export const SQAI_PLANNING_OPENAI_BASE_URL =
  'SQAI_PLANNING_OPENAI_BASE_URL';
export const SQAI_PLANNING_OPENAI_API_KEY =
  'SQAI_PLANNING_OPENAI_API_KEY';
export const SQAI_PLANNING_OPENAI_INIT_CONFIG_JSON =
  'SQAI_PLANNING_OPENAI_INIT_CONFIG_JSON';
export const SQAI_PLANNING_OPENAI_USE_AZURE =
  'SQAI_PLANNING_OPENAI_USE_AZURE';
export const SQAI_PLANNING_USE_AZURE_OPENAI =
  'SQAI_PLANNING_USE_AZURE_OPENAI';
export const SQAI_PLANNING_AZURE_OPENAI_SCOPE =
  'SQAI_PLANNING_AZURE_OPENAI_SCOPE';
export const SQAI_PLANNING_AZURE_OPENAI_KEY =
  'SQAI_PLANNING_AZURE_OPENAI_KEY';
export const SQAI_PLANNING_AZURE_OPENAI_ENDPOINT =
  'SQAI_PLANNING_AZURE_OPENAI_ENDPOINT';
export const SQAI_PLANNING_AZURE_OPENAI_API_VERSION =
  'SQAI_PLANNING_AZURE_OPENAI_API_VERSION';
export const SQAI_PLANNING_AZURE_OPENAI_DEPLOYMENT =
  'SQAI_PLANNING_AZURE_OPENAI_DEPLOYMENT';
export const SQAI_PLANNING_AZURE_OPENAI_INIT_CONFIG_JSON =
  'SQAI_PLANNING_AZURE_OPENAI_INIT_CONFIG_JSON';
export const SQAI_PLANNING_USE_ANTHROPIC_SDK =
  'SQAI_PLANNING_USE_ANTHROPIC_SDK';
export const SQAI_PLANNING_ANTHROPIC_API_KEY =
  'SQAI_PLANNING_ANTHROPIC_API_KEY';
export const SQAI_PLANNING_VL_MODE = 'SQAI_PLANNING_VL_MODE';

// GROUNDING
export const SQAI_GROUNDING_MODEL_NAME = 'SQAI_GROUNDING_MODEL_NAME';
export const SQAI_GROUNDING_OPENAI_SOCKS_PROXY =
  'SQAI_GROUNDING_OPENAI_SOCKS_PROXY';
export const SQAI_GROUNDING_OPENAI_HTTP_PROXY =
  'SQAI_GROUNDING_OPENAI_HTTP_PROXY';
export const SQAI_GROUNDING_OPENAI_BASE_URL =
  'SQAI_GROUNDING_OPENAI_BASE_URL';
export const SQAI_GROUNDING_OPENAI_API_KEY =
  'SQAI_GROUNDING_OPENAI_API_KEY';
export const SQAI_GROUNDING_OPENAI_INIT_CONFIG_JSON =
  'SQAI_GROUNDING_OPENAI_INIT_CONFIG_JSON';
export const SQAI_GROUNDING_OPENAI_USE_AZURE =
  'SQAI_GROUNDING_OPENAI_USE_AZURE';
export const SQAI_GROUNDING_USE_AZURE_OPENAI =
  'SQAI_GROUNDING_USE_AZURE_OPENAI';
export const SQAI_GROUNDING_AZURE_OPENAI_SCOPE =
  'SQAI_GROUNDING_AZURE_OPENAI_SCOPE';
export const SQAI_GROUNDING_AZURE_OPENAI_KEY =
  'SQAI_GROUNDING_AZURE_OPENAI_KEY';
export const SQAI_GROUNDING_AZURE_OPENAI_ENDPOINT =
  'SQAI_GROUNDING_AZURE_OPENAI_ENDPOINT';
export const SQAI_GROUNDING_AZURE_OPENAI_API_VERSION =
  'SQAI_GROUNDING_AZURE_OPENAI_API_VERSION';
export const SQAI_GROUNDING_AZURE_OPENAI_DEPLOYMENT =
  'SQAI_GROUNDING_AZURE_OPENAI_DEPLOYMENT';
export const SQAI_GROUNDING_AZURE_OPENAI_INIT_CONFIG_JSON =
  'SQAI_GROUNDING_AZURE_OPENAI_INIT_CONFIG_JSON';
export const SQAI_GROUNDING_USE_ANTHROPIC_SDK =
  'SQAI_GROUNDING_USE_ANTHROPIC_SDK';
export const SQAI_GROUNDING_ANTHROPIC_API_KEY =
  'SQAI_GROUNDING_ANTHROPIC_API_KEY';
export const SQAI_GROUNDING_VL_MODE = 'SQAI_GROUNDING_VL_MODE';

// @deprecated
export const OPENAI_USE_AZURE = 'OPENAI_USE_AZURE';

/**
 * env keys declared but unused
 */
export const UNUSED_ENV_KEYS = [SQAI_DANGEROUSLY_PRINT_ALL_CONFIG];

/**
 * env keys for debug or basic run
 * can not be override by overrideAIConfig
 */
export const BASIC_ENV_KEYS = [
  SQAI_DEBUG_MODE,
  SQAI_DEBUG_AI_PROFILE,
  SQAI_DEBUG_AI_RESPONSE,
  SQAI_RUN_DIR,
] as const;

export const BOOLEAN_ENV_KEYS = [
  SQAI_CACHE,
  SQAI_LANGSMITH_DEBUG,
  SQAI_FORCE_DEEP_THINK,
  SQAI_MCP_USE_PUPPETEER_MODE,
  SQAI_MCP_ANDROID_MODE,
] as const;

export const NUMBER_ENV_KEYS = [
  SQAI_CACHE_MAX_FILENAME_LENGTH,
  SQAI_REPLANNING_CYCLE_LIMIT,
] as const;

export const STRING_ENV_KEYS = [
  OPENAI_MAX_TOKENS,
  SQAI_ADB_PATH,
  SQAI_ADB_REMOTE_HOST,
  SQAI_ADB_REMOTE_PORT,
  SQAI_ANDROID_IME_STRATEGY,
  SQAI_IOS_DEVICE_UDID,
  SQAI_IOS_SIMULATOR_UDID,
  SQAI_REPORT_TAG_NAME,
  SQAI_PREFERRED_LANGUAGE,
  MATCH_BY_POSITION,
  SQAI_MCP_CHROME_PATH,
  DOCKER_CONTAINER,
] as const;

/**
 * Non model related env keys, used for globally controlling the behavior of midscene
 * Can not be override by agent.modelConfig but can be override by overrideAIConfig
 * Can be access at any time
 */
export const GLOBAL_ENV_KEYS = [
  ...BOOLEAN_ENV_KEYS,
  ...NUMBER_ENV_KEYS,
  ...STRING_ENV_KEYS,
] as const;

/**
 * Model related eve keys, used for declare which model to use.
 * Can be override by both agent.modelConfig and overrideAIConfig
 * Can only be access after agent.constructor
 */
export const MODEL_ENV_KEYS = [
  // model default
  SQAI_MODEL_NAME,
  SQAI_OPENAI_INIT_CONFIG_JSON,
  SQAI_OPENAI_API_KEY,
  SQAI_OPENAI_BASE_URL,
  SQAI_OPENAI_USE_AZURE,
  SQAI_OPENAI_SOCKS_PROXY,
  SQAI_OPENAI_HTTP_PROXY,
  SQAI_USE_AZURE_OPENAI,
  SQAI_AZURE_OPENAI_SCOPE,
  SQAI_AZURE_OPENAI_INIT_CONFIG_JSON,
  SQAI_USE_ANTHROPIC_SDK,
  SQAI_USE_VLM_UI_TARS,
  SQAI_USE_QWEN_VL,
  SQAI_USE_QWEN3_VL,
  SQAI_USE_DOUBAO_VISION,
  SQAI_USE_GEMINI,
  SQAI_USE_VL_MODEL,
  ANTHROPIC_API_KEY,
  SQAI_AZURE_OPENAI_ENDPOINT,
  SQAI_AZURE_OPENAI_KEY,
  SQAI_AZURE_OPENAI_API_VERSION,
  SQAI_AZURE_OPENAI_DEPLOYMENT,
  SQAI_VL_MODE,
  // model default legacy
  OPENAI_API_KEY,
  OPENAI_BASE_URL,
  OPENAI_USE_AZURE,
  ANTHROPIC_API_KEY,
  AZURE_OPENAI_ENDPOINT,
  AZURE_OPENAI_KEY,
  AZURE_OPENAI_API_VERSION,
  AZURE_OPENAI_DEPLOYMENT,
  // VQA
  SQAI_VQA_MODEL_NAME,
  SQAI_VQA_OPENAI_SOCKS_PROXY,
  SQAI_VQA_OPENAI_HTTP_PROXY,
  SQAI_VQA_OPENAI_BASE_URL,
  SQAI_VQA_OPENAI_API_KEY,
  SQAI_VQA_OPENAI_INIT_CONFIG_JSON,
  SQAI_VQA_OPENAI_USE_AZURE,
  SQAI_VQA_USE_AZURE_OPENAI,
  SQAI_VQA_AZURE_OPENAI_SCOPE,
  SQAI_VQA_AZURE_OPENAI_KEY,
  SQAI_VQA_AZURE_OPENAI_ENDPOINT,
  SQAI_VQA_AZURE_OPENAI_API_VERSION,
  SQAI_VQA_AZURE_OPENAI_DEPLOYMENT,
  SQAI_VQA_AZURE_OPENAI_INIT_CONFIG_JSON,
  SQAI_VQA_USE_ANTHROPIC_SDK,
  SQAI_VQA_ANTHROPIC_API_KEY,
  SQAI_VQA_VL_MODE,
  // PLANNING
  SQAI_PLANNING_MODEL_NAME,
  SQAI_PLANNING_OPENAI_SOCKS_PROXY,
  SQAI_PLANNING_OPENAI_HTTP_PROXY,
  SQAI_PLANNING_OPENAI_BASE_URL,
  SQAI_PLANNING_OPENAI_API_KEY,
  SQAI_PLANNING_OPENAI_INIT_CONFIG_JSON,
  SQAI_PLANNING_OPENAI_USE_AZURE,
  SQAI_PLANNING_USE_AZURE_OPENAI,
  SQAI_PLANNING_AZURE_OPENAI_SCOPE,
  SQAI_PLANNING_AZURE_OPENAI_KEY,
  SQAI_PLANNING_AZURE_OPENAI_ENDPOINT,
  SQAI_PLANNING_AZURE_OPENAI_API_VERSION,
  SQAI_PLANNING_AZURE_OPENAI_DEPLOYMENT,
  SQAI_PLANNING_AZURE_OPENAI_INIT_CONFIG_JSON,
  SQAI_PLANNING_USE_ANTHROPIC_SDK,
  SQAI_PLANNING_ANTHROPIC_API_KEY,
  SQAI_PLANNING_VL_MODE,
  // GROUNDING
  SQAI_GROUNDING_MODEL_NAME,
  SQAI_GROUNDING_OPENAI_SOCKS_PROXY,
  SQAI_GROUNDING_OPENAI_HTTP_PROXY,
  SQAI_GROUNDING_OPENAI_BASE_URL,
  SQAI_GROUNDING_OPENAI_API_KEY,
  SQAI_GROUNDING_OPENAI_INIT_CONFIG_JSON,
  SQAI_GROUNDING_OPENAI_USE_AZURE,
  SQAI_GROUNDING_USE_AZURE_OPENAI,
  SQAI_GROUNDING_AZURE_OPENAI_SCOPE,
  SQAI_GROUNDING_AZURE_OPENAI_KEY,
  SQAI_GROUNDING_AZURE_OPENAI_ENDPOINT,
  SQAI_GROUNDING_AZURE_OPENAI_API_VERSION,
  SQAI_GROUNDING_AZURE_OPENAI_DEPLOYMENT,
  SQAI_GROUNDING_AZURE_OPENAI_INIT_CONFIG_JSON,
  SQAI_GROUNDING_USE_ANTHROPIC_SDK,
  SQAI_GROUNDING_ANTHROPIC_API_KEY,
  SQAI_GROUNDING_VL_MODE,
] as const;

export const ALL_ENV_KEYS = [
  ...UNUSED_ENV_KEYS,
  ...BASIC_ENV_KEYS,
  ...GLOBAL_ENV_KEYS,
  ...MODEL_ENV_KEYS,
] as const;

export type TEnvKeys = (typeof ALL_ENV_KEYS)[number];
export type TGlobalConfig = Record<TEnvKeys, string | undefined>;

export type TVlModeValues =
  | 'qwen-vl'
  | 'qwen3-vl'
  | 'doubao-vision'
  | 'gemini'
  | 'vlm-ui-tars'
  | 'vlm-ui-tars-doubao'
  | 'vlm-ui-tars-doubao-1.5';

export type TVlModeTypes =
  | 'qwen-vl'
  | 'qwen3-vl'
  | 'doubao-vision'
  | 'gemini'
  | 'vlm-ui-tars';

export interface IModelConfigForVQA {
  // model name
  [SQAI_VQA_MODEL_NAME]: string;
  // proxy
  [SQAI_VQA_OPENAI_SOCKS_PROXY]?: string;
  [SQAI_VQA_OPENAI_HTTP_PROXY]?: string;
  // OpenAI
  [SQAI_VQA_OPENAI_BASE_URL]?: string;
  [SQAI_VQA_OPENAI_API_KEY]?: string;
  [SQAI_VQA_OPENAI_INIT_CONFIG_JSON]?: string;
  // Azure
  [SQAI_VQA_OPENAI_USE_AZURE]?: string;
  [SQAI_VQA_USE_AZURE_OPENAI]?: string;
  [SQAI_VQA_AZURE_OPENAI_SCOPE]?: string;
  [SQAI_VQA_AZURE_OPENAI_KEY]?: string;
  [SQAI_VQA_AZURE_OPENAI_ENDPOINT]?: string;
  [SQAI_VQA_AZURE_OPENAI_API_VERSION]?: string;
  [SQAI_VQA_AZURE_OPENAI_DEPLOYMENT]?: string;
  [SQAI_VQA_AZURE_OPENAI_INIT_CONFIG_JSON]?: string;
  // Anthropic
  [SQAI_VQA_USE_ANTHROPIC_SDK]?: string;
  [SQAI_VQA_ANTHROPIC_API_KEY]?: string;
  // extra
  [SQAI_VQA_VL_MODE]?: TVlModeValues;
}

export interface IModelConfigForPlanning {
  // model name
  [SQAI_PLANNING_MODEL_NAME]: string;
  // proxy
  [SQAI_PLANNING_OPENAI_SOCKS_PROXY]?: string;
  [SQAI_PLANNING_OPENAI_HTTP_PROXY]?: string;
  // OpenAI
  [SQAI_PLANNING_OPENAI_BASE_URL]?: string;
  [SQAI_PLANNING_OPENAI_API_KEY]?: string;
  [SQAI_PLANNING_OPENAI_INIT_CONFIG_JSON]?: string;
  // Azure
  [SQAI_PLANNING_OPENAI_USE_AZURE]?: string;
  [SQAI_PLANNING_USE_AZURE_OPENAI]?: string;
  [SQAI_PLANNING_AZURE_OPENAI_SCOPE]?: string;
  [SQAI_PLANNING_AZURE_OPENAI_KEY]?: string;
  [SQAI_PLANNING_AZURE_OPENAI_ENDPOINT]?: string;
  [SQAI_PLANNING_AZURE_OPENAI_API_VERSION]?: string;
  [SQAI_PLANNING_AZURE_OPENAI_DEPLOYMENT]?: string;
  [SQAI_PLANNING_AZURE_OPENAI_INIT_CONFIG_JSON]?: string;
  // Anthropic
  [SQAI_PLANNING_USE_ANTHROPIC_SDK]?: string;
  [SQAI_PLANNING_ANTHROPIC_API_KEY]?: string;
  // extra
  [SQAI_PLANNING_VL_MODE]?: TVlModeValues;
}

export interface IModeConfigForGrounding {
  // model name
  [SQAI_GROUNDING_MODEL_NAME]: string;
  // proxy
  [SQAI_GROUNDING_OPENAI_SOCKS_PROXY]?: string;
  [SQAI_GROUNDING_OPENAI_HTTP_PROXY]?: string;
  // OpenAI
  [SQAI_GROUNDING_OPENAI_BASE_URL]?: string;
  [SQAI_GROUNDING_OPENAI_API_KEY]?: string;
  [SQAI_GROUNDING_OPENAI_INIT_CONFIG_JSON]?: string;
  // Azure
  [SQAI_GROUNDING_OPENAI_USE_AZURE]?: string;
  [SQAI_GROUNDING_USE_AZURE_OPENAI]?: string;
  [SQAI_GROUNDING_AZURE_OPENAI_SCOPE]?: string;
  [SQAI_GROUNDING_AZURE_OPENAI_KEY]?: string;
  [SQAI_GROUNDING_AZURE_OPENAI_ENDPOINT]?: string;
  [SQAI_GROUNDING_AZURE_OPENAI_API_VERSION]?: string;
  [SQAI_GROUNDING_AZURE_OPENAI_DEPLOYMENT]?: string;
  [SQAI_GROUNDING_AZURE_OPENAI_INIT_CONFIG_JSON]?: string;
  // Anthropic
  [SQAI_GROUNDING_USE_ANTHROPIC_SDK]?: string;
  [SQAI_GROUNDING_ANTHROPIC_API_KEY]?: string;
  // extra
  [SQAI_GROUNDING_VL_MODE]?: TVlModeValues;
}

export interface IModelConfigForDefault {
  // model name
  [SQAI_MODEL_NAME]: string;
  // proxy
  [SQAI_OPENAI_SOCKS_PROXY]?: string;
  [SQAI_OPENAI_HTTP_PROXY]?: string;
  // OpenAI
  [SQAI_OPENAI_BASE_URL]?: string;
  [SQAI_OPENAI_API_KEY]?: string;
  [SQAI_OPENAI_INIT_CONFIG_JSON]?: string;
  // Azure
  [SQAI_OPENAI_USE_AZURE]?: string;
  [SQAI_USE_AZURE_OPENAI]?: string;
  [SQAI_AZURE_OPENAI_SCOPE]?: string;
  [SQAI_AZURE_OPENAI_KEY]?: string;
  [SQAI_AZURE_OPENAI_ENDPOINT]?: string;
  [SQAI_AZURE_OPENAI_API_VERSION]?: string;
  [SQAI_AZURE_OPENAI_DEPLOYMENT]?: string;
  [SQAI_AZURE_OPENAI_INIT_CONFIG_JSON]?: string;
  // Anthropic
  [SQAI_USE_ANTHROPIC_SDK]?: string;
  [SQAI_ANTHROPIC_API_KEY]?: string;
  // extra
  [SQAI_VL_MODE]?: TVlModeValues;
}

export interface IModelConfigForDefaultLegacy {
  // model name
  [SQAI_MODEL_NAME]: string;
  // proxy
  [SQAI_OPENAI_SOCKS_PROXY]?: string;
  [SQAI_OPENAI_HTTP_PROXY]?: string;
  // OpenAI
  [OPENAI_BASE_URL]?: string;
  [OPENAI_API_KEY]?: string;
  [SQAI_OPENAI_INIT_CONFIG_JSON]?: string;
  // Azure
  [OPENAI_USE_AZURE]?: string;
  [SQAI_USE_AZURE_OPENAI]?: string;
  [SQAI_AZURE_OPENAI_SCOPE]?: string;
  [AZURE_OPENAI_KEY]?: string;
  [AZURE_OPENAI_ENDPOINT]?: string;
  [AZURE_OPENAI_API_VERSION]?: string;
  [AZURE_OPENAI_DEPLOYMENT]?: string;
  [SQAI_AZURE_OPENAI_INIT_CONFIG_JSON]?: string;
  // Anthropic
  [SQAI_USE_ANTHROPIC_SDK]?: string;
  [ANTHROPIC_API_KEY]?: string;
  // extra
  [SQAI_VL_MODE]?: TVlModeValues;
}

/**
 * - VQA: Visual Question Answering
 * - grounding：short for Visual Grounding
 * - planning: planning
 * - default: all except VQA、grounding、planning
 */
export type TIntent = 'VQA' | 'planning' | 'grounding' | 'default';

export type TModelConfigFn = (options: {
  intent: TIntent;
}) =>
  | IModelConfigForVQA
  | IModelConfigForPlanning
  | IModeConfigForGrounding
  | IModelConfigForDefault;

export enum UITarsModelVersion {
  V1_0 = '1.0',
  V1_5 = '1.5',
  DOUBAO_1_5_15B = 'doubao-1.5-15B',
  DOUBAO_1_5_20B = 'doubao-1.5-20B',
}

export const VL_MODE_RAW_VALID_VALUES: TVlModeValues[] = [
  'doubao-vision',
  'gemini',
  'qwen-vl',
  'qwen3-vl',
  'vlm-ui-tars',
  'vlm-ui-tars-doubao',
  'vlm-ui-tars-doubao-1.5',
];

export interface IModelConfig {
  /**
   * proxy
   */
  socksProxy?: string;
  httpProxy?: string;
  /**
   * model
   */
  modelName: string;
  /**
   * OpenAI
   */
  openaiBaseURL?: string;
  openaiApiKey?: string;
  openaiExtraConfig?: Record<string, unknown>;
  /**
   * Azure
   */
  openaiUseAzureDeprecated?: boolean;
  useAzureOpenai?: boolean;
  azureOpenaiScope?: string;
  azureOpenaiKey?: string;
  azureOpenaiEndpoint?: string;
  azureOpenaiApiVersion?: string;
  azureOpenaiDeployment?: string;
  azureExtraConfig?: Record<string, unknown>;
  /**
   * Anthropic
   */
  useAnthropicSdk?: boolean;
  anthropicApiKey?: string;
  /**
   * - vlModeRaw: exists only in non-legacy logic. value can be 'doubao-vision', 'gemini', 'qwen-vl', 'vlm-ui-tars', 'vlm-ui-tars-doubao', 'vlm-ui-tars-doubao-1.5'
   * - vlMode: based on the results of the vlModoRaw classification，value can be 'doubao-vision', 'gemini', 'qwen-vl', 'vlm-ui-tars'
   */
  vlModeRaw?: string;
  vlMode?: TVlModeTypes;
  uiTarsModelVersion?: UITarsModelVersion;
  modelDescription: string;
  /**
   * for debug
   */
  intent: TIntent;
  from: 'modelConfig' | 'env' | 'legacy-env';
}
